## Title for Correlation and Distance.

In [1]:
%matplotlib inline

import matplotlib
import numpy as np
import scipy as sp
import matplotlib.pyplot as pl
from numpy import *
from math import *
from scipy import *
import numpy.linalg as linalg
from math import factorial
from math import exp
from math import log

def ang_cos(v1, v2):
    """ Get cos for similarity between two vectors"""
    cosang = np.dot(v1, v2)/(linalg.norm(v1) * linalg.norm(v2))
    return cosang




In [15]:
# ABDI P78
# Correlation

Notes = array([3,2,7,6,
             7,6,8,7,
             2,3,6,8,
             1,2,1,3,
             4,5,4,2,
             6,8,1,2,
             8,7,8,7,
             3,1,5,6,
             4,2,7,8,
             5,6,7,5])

Notes.shape = (10,4)

# Abdi method :
U = ones((1,10))
aMean = U.dot(Notes) / 10
print('Mean : ', aMean)

# Faster method from numpy
m = Notes.mean(0) # 0 to compute column wise mean (1 would have computed mean on lines)
m.shape = (1,4)
U = ones((10,1))
M = U.dot(m)
# Deviation Matrix is D = Notes - M

D = Notes - M
print('Deviation matrix: \n', D)



Mean :  [[ 4.3  4.2  5.4  5.4]]
Deviation matrix: 
 [[-1.3 -2.2  1.6  0.6]
 [ 2.7  1.8  2.6  1.6]
 [-2.3 -1.2  0.6  2.6]
 [-3.3 -2.2 -4.4 -2.4]
 [-0.3  0.8 -1.4 -3.4]
 [ 1.7  3.8 -4.4 -3.4]
 [ 3.7  2.8  2.6  1.6]
 [-1.3 -3.2 -0.4  0.6]
 [-0.3 -2.2  1.6  2.6]
 [ 0.7  1.8  1.6 -0.4]]
