In [3]:
%matplotlib inline

import matplotlib
import numpy as np
import scipy as sp
import matplotlib.pyplot as pl
from numpy import *
from math import *
from scipy import *
import numpy.linalg as linalg
from math import factorial
from math import exp
from math import log

def ang_cos(v1, v2):
    """ Get cos for similarity between two vectors"""
    cosang = np.dot(v1, v2)/(linalg.norm(v1) * linalg.norm(v2))
    return cosang



In [17]:
# Autoassociative Memory, learning via Widrow-Hoff Method.

# Associative memory Hebb learning (Abdi p. 58)
faces = array([1,1,1,-1,
            -1,-1,1,-1,
           -1,-1,-1,-1,
           1,-1,-1,1,
           -1,1,-1,-1,
           1,-1,1,1,
           1,1,1,1,
           -1,-1,-1,1,
           -1,1,1,-1,
           1,1,-1,1])
faces.shape = (10,4)
faces = faces.transpose()

faceSet = array([-1,-1,1,-1,
                1,-1,-1,1])
faceSet.shape = (2,4)
faceSet = faceSet.transpose()
print('faceSet: ', faceSet)

x1 = faces[:,1]
x1.shape = (4,1)
print('x1: ', x1)
x2 = faces[:,3]
x2.shape = (4,1)
print('x2: ', x2)


# now compute the associative Matrix iteratively
learningCoeff = 0.15
W = np.zeros((4,4))

ZEROS = np.zeros(shape(faceSet))

print('all zeros :', all(W)==0)
print('not any value : ', not any(W))

learnt = False
i = 0
#for i in range(0,30):
while learnt != True:
    WNext = W.dot(faceSet)
    #print('WNext: ', WNext)
    # Calculating the Error
    E = faceSet - WNext
    if allclose(E, ZEROS):
        print('************ ', i)
        learnt = True
    Delta = learningCoeff * (E.dot(faceSet.transpose()))
    W = W + Delta
    #print('Delta :', Delta)
    #print('W : ', W)
    i = i + 1

print('W for 2 faces:\n', W) # (Abdi p70)



# Now let's see if the memory can recall a well known face :
# To do so, we premultiply one of the faces by the connection matrix :
rem_1 = dot(W,x1)
print('remember 1: ', rem_1)

# To check the similarity with the original face, we just have to compute the cosine of the two vectors.
print('similarity of well-known face: ', ang_cos(x1.transpose(),rem_1))

# Now let's present an unknown face
unknown = array([1,-1,-1,-1])
rem_unknown = dot(W, unknown)
print('remember unknown ? : ', rem_unknown)
print('similarity of unknown face: ', ang_cos(unknown.transpose(), rem_unknown))

faceSet:  [[-1  1]
 [-1 -1]
 [ 1 -1]
 [-1  1]]
x1:  [[-1]
 [-1]
 [ 1]
 [-1]]
x2:  [[ 1]
 [-1]
 [-1]
 [ 1]]
all zeros : True
not any value :  True
************  52
W for 2 faces:
 [[ 0.33333333  0.         -0.33333333  0.33333333]
 [ 0.          0.99999999  0.          0.        ]
 [-0.33333333  0.          0.33333333 -0.33333333]
 [ 0.33333333  0.         -0.33333333  0.33333333]]
remember 1:  [[-1.        ]
 [-0.99999999]
 [ 1.        ]
 [-1.        ]]
similarity of well-known face:  [[ 1.]]
remember unknown ? :  [ 0.33333333 -0.99999999 -0.33333333  0.33333333]
similarity of unknown face:  0.57735026919


In [20]:
# Same with 10 faces
# now compute the associative Matrix iteratively

print('faces ', faces)

learningCoeff = 0.01
W = np.zeros((4,4))
ZEROS = np.zeros(faces.shape)

learnt = False
iteration = 0
#for i in range(0,30):
while learnt != True and iteration < 3000:
    WNext = W.dot(faces)
    #print('WNext: ', WNext)
    # Calculating the Error
    E = faces - WNext
    print('E: ', E)
    if allclose(E,ZEROS):
        print('************ ', iteration)
        learnt = True
    Delta = learningCoeff * (E.dot(faces.transpose()))
    W = W + Delta
    #print('Delta :', Delta)
    #print('W : ', W)
    iteration = iteration + 1

print('W for 10 faces:\n', W) 



# Now let's see if the memory can recall a well known face :
# To do so, we premultiply one of the faces by the connection matrix :
rem_1 = dot(W,x1)
print('remember 1: ', rem_1)

# To check the similarity with the original face, we just have to compute the cosine of the two vectors.
print('similarity of well-known face: ', ang_cos(x1.transpose(),rem_1))

# Now let's present an unknown face
#unknown = array([1,-1,-1,-1])
unknown = array([1,1,1,1])
rem_unknown = dot(W, unknown)
print('remember unknown ? : ', rem_unknown)
print('similarity of unknown face: ', ang_cos(unknown.transpose(), rem_unknown))

#### PROBLEM : The weight matrix returns false positive... exactly as my brain would react to :)
# Should we need to train it less ? more ? Or to also learn this falsy results ?
print('Problem ? mismatch !')

faces  [[ 1 -1 -1  1 -1  1  1 -1 -1  1]
 [ 1 -1 -1 -1  1 -1  1 -1  1  1]
 [ 1  1 -1 -1 -1  1  1 -1  1 -1]
 [-1 -1 -1  1 -1  1  1  1 -1  1]]
E:  [[ 1. -1. -1.  1. -1.  1.  1. -1. -1.  1.]
 [ 1. -1. -1. -1.  1. -1.  1. -1.  1.  1.]
 [ 1.  1. -1. -1. -1.  1.  1. -1.  1. -1.]
 [-1. -1. -1.  1. -1.  1.  1.  1. -1.  1.]]
E:  [[ 0.92 -0.84 -0.8   0.88 -0.84  0.84  0.8  -0.92 -0.88  0.84]
 [ 0.84 -0.92 -0.88 -0.88  0.92 -0.92  0.88 -0.84  0.88  0.92]
 [ 0.84  0.92 -0.88 -0.88 -0.92  0.92  0.88 -0.84  0.88 -0.92]
 [-0.92 -0.84 -0.88  0.8  -0.84  0.84  0.88  0.92 -0.8   0.84]]
E:  [[ 0.8496 -0.7056 -0.632   0.7792 -0.7056  0.7056  0.632  -0.8496 -0.7792
   0.7056]
 [ 0.7024 -0.8464 -0.776  -0.776   0.8464 -0.8464  0.776  -0.7024  0.776
   0.8464]
 [ 0.7024  0.8464 -0.776  -0.776  -0.8464  0.8464  0.776  -0.7024  0.776
  -0.8464]
 [-0.8496 -0.7056 -0.7792  0.632  -0.7056  0.7056  0.7792  0.8496 -0.632
   0.7056]]
E:  [[ 0.78752  -0.592704 -0.491008  0.6944   -0.592704  0.592704  0.491008
  -0.787