In [1]:
%matplotlib inline

import matplotlib
import numpy as np
import scipy as sp
import matplotlib.pyplot as pl
from numpy import *
from math import *
from scipy import *
import numpy.linalg as linalg
from math import factorial
from math import exp
from math import log

def ang_cos(v1, v2):
    """ Get cos for similarity between two vectors"""
    cosang = np.dot(v1, v2)/(linalg.norm(v1) * linalg.norm(v2))
    return cosang



In [22]:
# Autoassociative Memory, learning via Widrow-Hoff Method.

# Associative memory Hebb learning (Abdi p. 58)
facesToLearn = array([1,-1,1,-1,
                      -1,-1,1,-1,
                      -1,-1,-1,-1,
                       1,-1,-1,1,
                       -1,1,-1,-1])
facesToLearn.shape = (5,4)
facesToLearn = facesToLearn.transpose()

namesToLearn = array([1,1,-1,
                -1,1,-1,
                -1,-1,1,
                1,-1,1,
                -1,1,1])
namesToLearn.shape = (5,3)
namesToLearn = namesToLearn.transpose()

print('names : \n', namesToLearn)

# We could then iterate : Wn+1 = Wn + facetolearn(i).namestolearn(i)T
# Like autoassociative memory we can simply multiply facestolearn with namestolearnT to get the same W matrix

W = facesToLearn.dot(namesToLearn.transpose())

print('Weight Matrix W = \n', W)

#Lets compute at the same time all the names recognized by the memory :
facesFound = W.transpose().dot(facesToLearn)

print('Faces found : \n', facesFound)

# now compute the associative Matrix iteratively
# Widrow-Hoff learning

learningCoeff = 0.01
W_WH = np.zeros((4,3))
ZEROS = np.zeros((namesToLearn.shape))
learnt = False
iteration = 0
#for i in range(0,30):
while learnt != True and iteration < 3000000:
    WNext = W_WH.transpose().dot(facesToLearn)
    # Calculating the Error
    E =  WNext - namesToLearn
    #if E.any() == 0:
    if allclose(E,ZEROS):
        print('************ ', iteration)
        learnt = True
    Delta = learningCoeff * (E.dot(facesToLearn.transpose()))
    W_WH = W_WH - Delta.transpose()
    #print('Delta :', Delta)
    if iteration%100000 == 0:
        print('WNext: ', WNext)
        print('Error : \n', E)
        print('Wi : ',iteration , '\n', W_WH)
    iteration = iteration + 1

print('W Widrow-Hoff for 5 faces:\n', W_WH) 


print('names : \n', namesToLearn)


# Now let's see if the memory can recall a well known face :
rememberFaces = W_WH.transpose().dot(facesToLearn)
print('remember 1: \n', rememberFaces)

# To check the similarity with the original face, we just have to compute the cosine of the two vectors.
for i in range(0,5):
    print('similarity of well-known face',i,' : ', ang_cos(rememberFaces[:,i].transpose(),namesToLearn[:,i]))

# Now let's present an unknown face
#unknown = array([1,-1,-1,-1])
unknown = array([-1,1,1,1])
rem_unknown = W_WH.transpose().dot(unknown)
print('remember unknown ? : ', rem_unknown)
for i in range(0,5):
    print('similarity of unknown face: ', ang_cos(rem_unknown.transpose(), namesToLearn[:,i]))

#### PROBLEM : The weight matrix returns false positive... exactly az my brain would react to :)
# Should we need to train it less ? more ? Or to also learn this falsy results ?
print('Problem ? mismatch !')


names : 
 [[ 1 -1 -1  1 -1]
 [ 1  1 -1 -1  1]
 [-1 -1  1  1  1]]
Weight Matrix W = 
 [[ 5 -1 -1]
 [-1  1  1]
 [ 1  3 -5]
 [ 3 -3  1]]
Faces found : 
 [[  4  -6  -8   8 -10]
 [  4   6   0  -8   2]
 [ -8  -6   4   4   6]]
WNext:  [[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Error : 
 [[-1.  1.  1. -1.  1.]
 [-1. -1.  1.  1. -1.]
 [ 1.  1. -1. -1. -1.]]
Wi :  0 
 [[ 0.05 -0.01 -0.01]
 [-0.01  0.01  0.01]
 [ 0.01  0.03 -0.05]
 [ 0.03 -0.03  0.01]]
WNext:  [[ 1.  -1.  -1.   1.  -1. ]
 [ 1.   0.5 -0.5 -1.5  0.5]
 [-1.  -1.   1.   1.   1. ]]
Error : 
 [[ -2.66453526e-15   1.99840144e-15   6.66133815e-16  -6.66133815e-16
   -6.66133815e-16]
 [ -3.10862447e-15  -5.00000000e-01   5.00000000e-01  -5.00000000e-01
   -5.00000000e-01]
 [  0.00000000e+00   1.33226763e-15  -1.33226763e-15  -1.33226763e-15
   -1.33226763e-15]]
Wi :  100000 
 [[  1.00000000e+00   2.50000000e-01  -7.18238959e-16]
 [ -6.68564193e-16   5.00000000e-01   6.73850649e-19]
 [  7.17475520e-16   5.0000000

KeyboardInterrupt: 