In [2]:
%matplotlib inline

import matplotlib
import numpy as np
import scipy as sp
import matplotlib.pyplot as pl
from numpy import *
from math import *
from scipy import *
import numpy.linalg as linalg
from math import factorial
from math import exp
from math import log

def ang_cos(v1, v2):
    """ Get cos for similarity between two vectors"""
    cosang = np.dot(v1, v2)/(linalg.norm(v1) * linalg.norm(v2))
    return cosang



In [7]:
# Autoassociative Memory, learning via Widrow-Hoff Method.

# Associative memory Hebb learning (Abdi p. 58)
faces = array([1,1,1,-1,
            -1,-1,1,-1,
           -1,-1,-1,-1,
           1,-1,-1,1,
           -1,1,-1,-1,
           1,-1,1,1,
           1,1,1,1,
           -1,-1,-1,1,
           -1,1,1,-1,
           1,1,-1,1])
faces.shape = (10,4)
faces = faces.transpose()

faceSet = array([-1,-1,1,-1,
                1,-1,-1,1])
faceSet.shape = (2,4)
faceSet = faceSet.transpose()
print('faceSet: ', faceSet)

x1 = faces[:,1]
x1.shape = (4,1)
print('x1: ', x1)
x2 = faces[:,3]
x2.shape = (4,1)
print('x2: ', x2)


# now compute the associative Matrix iteratively
learningCoeff = 0.15
W = np.zeros((4,4))
learnt = False
i = 0
#for i in range(0,30):
while learnt != True:
    WNext = W.dot(faceSet)
    #print('WNext: ', WNext)
    # Calculating the Error
    E = faceSet - WNext
    if E.all() == 0:
        print('************ ', i)
        learnt = True
    Delta = learningCoeff * (E.dot(faceSet.transpose()))
    W = W + Delta
    #print('Delta :', Delta)
    #print('W : ', W)
    i = i + 1

print('W for 2 faces:\n', W) # (Abdi p70)



# Now let's see if the memory can recall a well known face :
# To do so, we premultiply one of the faces by the connection matrix :
rem_1 = dot(W,x1)
print('remember 1: ', rem_1)

# To check the similarity with the original face, we just have to compute the cosine of the two vectors.
print('similarity of well-known face: ', ang_cos(x1.transpose(),rem_1))

# Now let's present an unknown face
unknown = array([1,-1,-1,-1])
rem_unknown = dot(W, unknown)
print('remember unknown ? : ', rem_unknown)
print('similarity of unknown face: ', ang_cos(unknown.transpose(), rem_unknown))


# Same with 10 faces
# now compute the associative Matrix iteratively

print('faces ', faces)

learningCoeff = 0.001
W = np.zeros((4,4))
learnt = False
iteration = 0
#for i in range(0,30):
while learnt != True and iteration < 10000:
    WNext = W.dot(faces)
    print('WNext: ', WNext)
    # Calculating the Error
    E = faces - WNext
    if E.all() == 0:
        print('************ ', iteration)
        learnt = True
    Delta = learningCoeff * (E.dot(faces.transpose()))
    W = W + Delta
    #print('Delta :', Delta)
    #print('W : ', W)
    iteration = iteration + 1

print('W for 10 faces:\n', W) 



# Now let's see if the memory can recall a well known face :
# To do so, we premultiply one of the faces by the connection matrix :
rem_1 = dot(W,x1)
print('remember 1: ', rem_1)

# To check the similarity with the original face, we just have to compute the cosine of the two vectors.
print('similarity of well-known face: ', ang_cos(x1.transpose(),rem_1))

# Now let's present an unknown face
#unknown = array([1,-1,-1,-1])
unknown = array([1,1,1,1])
rem_unknown = dot(W, unknown)
print('remember unknown ? : ', rem_unknown)
print('similarity of unknown face: ', ang_cos(unknown.transpose(), rem_unknown))

#### PROBLEM : The weight matrix returns false positive... exactly az my brain would react to :)
# Should we need to train it less ? more ? Or to also learn this falsy results ?
print('Problem ? mismatch !')


faceSet:  [[-1  1]
 [-1 -1]
 [ 1 -1]
 [-1  1]]
x1:  [[-1]
 [-1]
 [ 1]
 [-1]]
x2:  [[ 1]
 [-1]
 [-1]
 [ 1]]
************  16
W for 2 faces:
 [[ 0.33333333  0.         -0.33333333  0.33333333]
 [ 0.          0.99767369  0.          0.        ]
 [-0.33333333  0.          0.33333333 -0.33333333]
 [ 0.33333333  0.         -0.33333333  0.33333333]]
remember 1:  [[-1.        ]
 [-0.99767369]
 [ 1.        ]
 [-1.        ]]
similarity of well-known face:  [[ 0.99999949]]
remember unknown ? :  [ 0.33333333 -0.99767369 -0.33333333  0.33333333]
similarity of unknown face:  0.577349975248
faces  [[ 1 -1 -1  1 -1  1  1 -1 -1  1]
 [ 1 -1 -1 -1  1 -1  1 -1  1  1]
 [ 1  1 -1 -1 -1  1  1 -1  1 -1]
 [-1 -1 -1  1 -1  1  1  1 -1  1]]
WNext:  [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
WNext:  [[ 0.008 -0.016 -0.02   0.012 -0.016  0.016  0.02  -0.008 -0.012  0.016]
 [ 0.016 -0.008