## Inverse, eigen value and vector

In [18]:
%matplotlib inline

import sys
import matplotlib
import numpy as np
import scipy as sp
import matplotlib.pyplot as pl
from numpy import *
from math import *
from scipy import *
import numpy.linalg as linalg
from math import factorial
from math import exp
from math import log


def ang_cos(v1, v2):
    """ Get cos for similarity between two vectors"""
    cosang = np.dot(v1, v2)/(linalg.norm(v1) * linalg.norm(v2))
    return cosang


# Create a myDiag function to do the job
def createDiagonalMatrix(v):
    M = zeros((v.size, v.size))
    for i in range(v.size):
        M[i,i] = v[0,i]
    return M

def extractDiagonal(M):
    # TODO  : create a variable length vector.. ??
    v = np.zeros((1,M.shape[0]))
    for i in range (M.shape[0]):
        v[0,i] = M[i,i]
    return v


In [19]:
A = array([
        1, 2, 1,
        0, 1, 0,
        0, 0, 1
    ])

A.shape = (3,3)

if linalg.cond(A) < 1/sys.float_info.epsilon:
    Ai = linalg.inv(A)
    print('inverse of A: \n', Ai) 
    print('check: \n', Ai.dot(A))
else:
    print('This matrix can''t be inverted')

inverse of A: 
 [[ 1. -2. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
check: 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [20]:
B = array([
        3,4,2,
        1,0,2,
        2,1,3
    ])

B.shape = (3,3)
if linalg.cond(B) < 1/sys.float_info.epsilon:
    Bi = linalg.inv(B)
    print('inverse of B: \n', Bi) 
    print('check: \n', Bi.dot(B))
else:
    print('This matrix can''t be inverted')
    


This matrix cant be inverted


In [30]:
v = array([1,0.5,4])
v.shape = (1,3)
M = createDiagonalMatrix(v)
Mi = linalg.inv(M)
print('inverse of diagonal matrix \n ', M, ' = \n', Mi)
print('simply inverse of each diagonal term')



inverse of diagonal matrix 
  [[ 1.   0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.   0.   4. ]]  = 
 [[ 1.    0.    0.  ]
 [ 0.    2.    0.  ]
 [ 0.    0.    0.25]]
simply inverse of each diagonal term
inverse :  [[ 1.     inf   inf]
 [  inf  2.     inf]
 [  inf   inf  0.25]]


C:\Users\nmauger\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: RuntimeWarning: divide by zero encountered in true_divide


In [38]:
#Orthonormal matrix
A = array([
        .5, -.5, -.5, -.5,
        .5, .5, -.5, .5,
        .5, -.5, .5, .5,
        .5, .5, .5, -.5
    ])

A.shape = (4,4)

print('AT.A :\n', A.transpose().dot(A))
print('AT.A == A.AT == I', A.transpose().dot(A) == A.dot(A.transpose()))


AT.A :
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
AT.A == A.AT == I [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
