## Inverse, eigen value and vector

In [2]:
%matplotlib inline

import matplotlib
import numpy as np
import scipy as sp
import matplotlib.pyplot as pl
from numpy import *
from math import *
from scipy import *
import numpy.linalg as linalg
from math import factorial
from math import exp
from math import log

def ang_cos(v1, v2):
    """ Get cos for similarity between two vectors"""
    cosang = np.dot(v1, v2)/(linalg.norm(v1) * linalg.norm(v2))
    return cosang




In [8]:
A = array([
        1, 2, 1,
        0, 1, 0,
        0, 0, 1
    ])

A.shape = (3,3)

Ai = linalg.inv(A)
print('inverse of A: \n', Ai)

print('check: \n', Ai.dot(A))

inverse of A: 
 [[ 1. -2. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
check: 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
