In [1]:
%matplotlib inline

import matplotlib
import numpy as np
import scipy as sp
import matplotlib.pyplot as pl
from numpy import *
from math import *
from scipy import *
import numpy.linalg as linalg
from math import factorial
from math import exp
from math import log

def ang_cos(v1, v2):
    """ Get cos for similarity between two vectors"""
    cosang = np.dot(v1, v2)/(linalg.norm(v1) * linalg.norm(v2))
    return cosang




In [31]:
# ABDI P78
# Correlation

Notes = array([3,2,7,6,
             7,6,8,7,
             2,3,6,8,
             1,2,1,3,
             4,5,4,2,
             6,8,1,2,
             8,7,8,7,
             3,1,5,6,
             4,2,7,8,
             5,6,7,5])

Notes.shape = (10,4)

# Abdi method :
U = ones((1,10))
aMean = U.dot(Notes) / 10
print('Mean : ', aMean)

# Faster method from numpy
m = Notes.mean(0) # 0 to compute column wise mean (1 would have computed mean on lines)
m.shape = (1,4)
U = ones((10,1))
M = U.dot(m)
# Deviation Matrix is D = Notes - M

D = Notes - M
print('Deviation matrix: \n', D)



Mean :  [[ 4.3  4.2  5.4  5.4]]
Deviation matrix: 
 [[-1.3 -2.2  1.6  0.6]
 [ 2.7  1.8  2.6  1.6]
 [-2.3 -1.2  0.6  2.6]
 [-3.3 -2.2 -4.4 -2.4]
 [-0.3  0.8 -1.4 -3.4]
 [ 1.7  3.8 -4.4 -3.4]
 [ 3.7  2.8  2.6  1.6]
 [-1.3 -3.2 -0.4  0.6]
 [-0.3 -2.2  1.6  2.6]
 [ 0.7  1.8  1.6 -0.4]]


In [32]:
# Lets compute the "variance" of the matrix
# Then the "ecart type"
I = ones((1,10))
s = I.dot((D*D))/10
print('Variance: ' , s)
t = sqrt(s)
print('Ecart-type: ', t)
u = 1/t
print('inverse of Ecart-Type: ', u)


Variance:  [[ 4.41  5.56  6.24  4.84]]
Ecart-type:  [[ 2.1         2.35796522  2.4979992   2.2       ]]
inverse of Ecart-Type:  [[ 0.47619048  0.42409446  0.40032038  0.45454545]]


In [104]:
# Z Matrix

# how to create a diagonal matrix from a vector ? 
# TODO :  don't know, so first, do it manually
du = diag(u) # --> This do not work
print('diag(u): ',du)
# Let's do it manually
du = zeros((4,4))
for i in range(u.size):
    du[i,i] = u[0,i]
print('diag(u): ',du)

# Create a myDiag function to do the job
def myDiag(v):
    M = zeros((v.size, v.size))
    for i in range(v.size):
        M[i,i] = v[0,i]
    return M

def extractDiag(M):
    # TODO  : create a variable length vector.. ??
    v = np.zeros((1,M.shape[0]))
    for i in range (M.shape[0]):
        v[0,i] = M[i,i]
        print('vx:', v[0,i], ' / ', M.shape[0])
    return v

print('my diag(u) :', myDiag(u))
print('diag(diag(u)) :', extractDiag(du))
Z = D.dot(du)
print('Z Notes: ', Z)


diag(u):  [ 0.47619048]
diag(u):  [[ 0.47619048  0.          0.          0.        ]
 [ 0.          0.42409446  0.          0.        ]
 [ 0.          0.          0.40032038  0.        ]
 [ 0.          0.          0.          0.45454545]]
my diag(u) : [[ 0.47619048  0.          0.          0.        ]
 [ 0.          0.42409446  0.          0.        ]
 [ 0.          0.          0.40032038  0.        ]
 [ 0.          0.          0.          0.45454545]]
vx: 0.47619047619  /  4
vx: 0.42409446484  /  4
vx: 0.400320384513  /  4
vx: 0.454545454545  /  4
diag(diag(u)) : [[ 0.47619048  0.42409446  0.40032038  0.45454545]]
Z Notes:  [[-0.61904762 -0.93300782  0.64051262  0.27272727]
 [ 1.28571429  0.76337004  1.040833    0.72727273]
 [-1.0952381  -0.50891336  0.24019223  1.18181818]
 [-1.57142857 -0.93300782 -1.76140969 -1.09090909]
 [-0.14285714  0.33927557 -0.56044854 -1.54545455]
 [ 0.80952381  1.61155897 -1.76140969 -1.54545455]
 [ 1.76190476  1.1874645   1.040833    0.72727273]
 [-0.61904

In [95]:
# Correlation matrix: Cross product of Z divided by the number of notes.
# R = 1/10 ZtZ

In [55]:
R = (Z.transpose().dot(Z))/10
print('R Matrix: ', R)

R Matrix:  [[ 1.          0.81587697  0.41557068  0.1038961 ]
 [ 0.81587697  1.          0.00339547 -0.30457693]
 [ 0.41557068  0.00339547  1.          0.80791932]
 [ 0.1038961  -0.30457693  0.80791932  1.        ]]


In [59]:
# Comparing observations
X = array([
        1,1,1,-1,
        -1,-1,1,-1,
        -1,-1,-1,-1,
        1,-1,-1,1,
        -1,1,-1,-1
    ])

X.shape = (4,5)
S = X.transpose().dot(X)
print('S: ', S)


S:  [[ 4  0  2  0  0]
 [ 0  4 -2  0  0]
 [ 2 -2  4 -2 -2]
 [ 0  0 -2  4  4]
 [ 0  0 -2  4  4]]
