In [2]:
%matplotlib inline

import matplotlib
import numpy as np
import scipy as sp
import matplotlib.pyplot as pl
from numpy import *
from math import *
from scipy import *
import numpy.linalg as linalg
from math import factorial
from math import exp
from math import log

def ang_cos(v1, v2):
    """ Get cos for similarity between two vectors"""
    cosang = np.dot(v1, v2)/(linalg.norm(v1) * linalg.norm(v2))
    return cosang



In [23]:
# Autoassociative Memory, learning via Widrow-Hoff Method.

# Associative memory Hebb learning (Abdi p. 58)
facesToLearn = array([1,1,1,-1,
                      -1,-1,1,-1,
                      -1,-1,-1,-1,
                       1,-1,-1,1,
                       -1,1,-1,-1])
facesToLearn.shape = (5,4)
facesToLearn = facesToLearn.transpose()

namesToLearn = array([1,1,-1,
                -1,1,-1,
                -1,-1,1,
                1,-1,1,
                -1,1,1])
namesToLearn.shape = (5,3)
namesToLearn = namesToLearn.transpose()

print('names : \n', namesToLearn)

# We could then iterate : Wn+1 = Wn + facetolearn(i).namestolearn(i)T
# Like autoassociative memory we can simply multiply facestolearn with namestolearnT to get the same W matrix

W = facesToLearn.dot(namesToLearn.transpose())

print('Weight Matrix W = \n', W)

#Lets compute at the same time all the names recognized by the memory :
facesFound = W.transpose().dot(facesToLearn)

print('Faces found : \n', facesFound)

# now compute the associative Matrix iteratively
# Widrow-Hoff learning

learningCoeff = 0.1
W_WH = np.zeros((4,3))
learnt = False
iteration = 0
#for i in range(0,30):
while learnt != True and iteration < 1000:
    WNext = W_WH.transpose().dot(facesToLearn)
    print('WNext: ', WNext)
    # Calculating the Error
    E = namesToLearn - WNext
    print('Error : \n', E)
    if E.any() == 0:
        print('************ ', iteration)
        learnt = True
    Delta = learningCoeff * (E.dot(facesToLearn.transpose()))
    W_WH = W_WH + Delta.transpose()
    #print('Delta :', Delta)
    print('Wi : ',iteration , '\n', W)
    iteration = iteration + 1

print('W Widrow-Hoff for 5 faces:\n', W_WH) 


print('names : \n', namesToLearn)


# Now let's see if the memory can recall a well known face :
rememberFaces = W_WH.transpose().dot(facesToLearn)
print('remember 1: ', rememberFaces)

# To check the similarity with the original face, we just have to compute the cosine of the two vectors.
for i in range(0,5):
    print('similarity of well-known face',i,' : ', ang_cos(rememberFaces[:,i].transpose(),namesToLearn[:,i]))

# Now let's present an unknown face
#unknown = array([1,-1,-1,-1])
unknown = array([1,1,1,1])
rem_unknown = W_WH.transpose().dot(unknown)
print('remember unknown ? : ', rem_unknown)
for i in range(0,5):
    print('similarity of unknown face: ', ang_cos(rem_unknown.transpose(), namesToLearn[:,i]))

#### PROBLEM : The weight matrix returns false positive... exactly az my brain would react to :)
# Should we need to train it less ? more ? Or to also learn this falsy results ?
print('Problem ? mismatch !')


names : 
 [[ 1 -1 -1  1 -1]
 [ 1  1 -1 -1  1]
 [-1 -1  1  1  1]]
Weight Matrix W = 
 [[ 5 -1 -1]
 [ 1  3 -1]
 [ 1  3 -5]
 [ 3 -3  1]]
Faces found : 
 [[  4  -8 -10   6  -8]
 [  8   4  -2 -10   4]
 [ -8  -4   6   6   4]]
WNext:  [[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Error : 
 [[ 1. -1. -1.  1. -1.]
 [ 1.  1. -1. -1.  1.]
 [-1. -1.  1.  1.  1.]]
Wi :  0 
 [[ 5 -1 -1]
 [ 1  3 -1]
 [ 1  3 -5]
 [ 3 -3  1]]
WNext:  [[ 0.4 -0.8 -1.   0.6 -0.8]
 [ 0.8  0.4 -0.2 -1.   0.4]
 [-0.8 -0.4  0.6  0.6  0.4]]
Error : 
 [[ 0.6 -0.2  0.   0.4 -0.2]
 [ 0.2  0.6 -0.8  0.   0.6]
 [-0.2 -0.6  0.4  0.4  0.6]]
Wi :  1 
 [[ 5 -1 -1]
 [ 1  3 -1]
 [ 1  3 -5]
 [ 3 -3  1]]
WNext:  [[ 0.56 -0.96 -1.2   0.72 -0.96]
 [ 1.04  0.48 -0.32 -1.28  0.48]
 [-1.04 -0.64  0.8   0.8   0.64]]
Error : 
 [[ 0.44 -0.04  0.2   0.28 -0.04]
 [-0.04  0.52 -0.68  0.28  0.52]
 [ 0.04 -0.36  0.2   0.2   0.36]]
Wi :  2 
 [[ 5 -1 -1]
 [ 1  3 -1]
 [ 1  3 -5]
 [ 3 -3  1]]
WNext:  [[ 0.64  -0.992 -1.224  0.76  -