In [2]:
# Python is slow for repeated low level execution tasks

def func_python(N):
    d = 0.0
    for i in range(N):
        d += (i % 3 - i) * i
    return d

%timeit func_python(1000000)


10 loops, best of 3: 184 ms per loop


In [5]:
# Using NUMPY, ufunc
a = list(range(100000)) #[1,3,2,4,3,1,4,2]
b = []
%timeit b = [val + 5 for val in a]
print(b)


100 loops, best of 3: 4.25 ms per loop
[]


In [6]:
import numpy as np
a = np.array(a)
%timeit b = a + 5
print(b)

10000 loops, best of 3: 43.1 µs per loop
[]


In [7]:
# Using NUMPY aggregations (min, max, mean, sum...)
from random import random
c = [random() for i in range(100000)]
%timeit min(c)


1000 loops, best of 3: 1.51 ms per loop


In [8]:
c = np.array(c)
%timeit c.min()


The slowest run took 161.82 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 23.3 µs per loop


In [9]:
def func_pythonNP(N):
    d = 0.0
    n = np.arange(N)
    #for i in range(N):
    #    d += (i % 3 - i) * i
    a = ((n % 3 - n) * n).sum()
    
    return a

%timeit func_pythonNP(1000000)

100 loops, best of 3: 9.11 ms per loop


In [10]:
# Broadcasting
# rules by which ufuncs operates on arrays of different dimensions...



In [11]:
# slicing, masking and fancy indexing.
L = np.array([1,4,7,9,10])
mask = (L < 4) | (L > 8)
print(mask)
print(L[mask])

[ True False False  True  True]
[ 1  9 10]


In [12]:
# fancy indexin
ind = [0,4,2]
L[ind]


array([ 1, 10,  7])

In [49]:
# Broadcasting tests
a = np.random.random((10,3))
print(a)
print('argmin : {}'.format(np.argmin(a)))
print('argmin along row  : {}'.format(np.argmin(a,0)))
print('argmin along col  : {}'.format(np.argmin(a,1)))

a = np.arange(24)
a = a.reshape([2,3,4])
b = np.arange(100,108)
b = b.reshape([2,1,4])
print('a : {}'.format(a))
print('b : {}'.format(b))
c = a + b
print('a +  b : {}'.format(a+b))
print('b +  a : {}'.format(b+a))

[[ 0.6947258   0.36393919  0.43638258]
 [ 0.32590993  0.80631709  0.11262618]
 [ 0.2098056   0.02756665  0.6871352 ]
 [ 0.41056228  0.36958263  0.29266267]
 [ 0.91543312  0.2537593   0.79081027]
 [ 0.14080884  0.29070604  0.41662942]
 [ 0.10302157  0.29848245  0.75834246]
 [ 0.46940703  0.21541219  0.24779274]
 [ 0.3332061   0.6162073   0.9668033 ]
 [ 0.51777598  0.85851568  0.83598772]]
argmin : 7
argmin along row  : [6 2 1]
argmin along col  : [1 2 1 2 1 0 0 1 0 0]
a : [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b : [[[100 101 102 103]]

 [[104 105 106 107]]]
c : [[[100 102 104 106]
  [104 106 108 110]
  [108 110 112 114]]

 [[116 118 120 122]
  [120 122 124 126]
  [124 126 128 130]]]


In [47]:
# Full example : nearest neighbour
NB_POINTS = 3

X = np.random.random((NB_POINTS, 3))
print('X.shape : {}'.format(X.shape))
XR = X.reshape(NB_POINTS,1,3)
print('X : {}'.format(X))
print('XR : {}'.format(XR))
diff = XR - X

print('Diff.shape : {}'.format(diff.shape))
print(diff)

D = (diff **2).sum(2)
D.shape

i = np.arange(NB_POINTS)
D[i,i] = np.inf
print('Distance:\n {}'.format(D))

i = np.argmin(D, 1)
print('i : {}'.format(i))
print('i[:n] : {}'.format(i[:10]))

X.shape : (3, 3)
X : [[ 0.99425153  0.8142761   0.74002536]
 [ 0.62313503  0.05219316  0.14505512]
 [ 0.96967017  0.75060518  0.51321786]]
XR : [[[ 0.99425153  0.8142761   0.74002536]]

 [[ 0.62313503  0.05219316  0.14505512]]

 [[ 0.96967017  0.75060518  0.51321786]]]
Diff.shape : (3, 3, 3)
[[[ 0.          0.          0.        ]
  [ 0.37111649  0.76208294  0.59497023]
  [ 0.02458136  0.06367092  0.2268075 ]]

 [[-0.37111649 -0.76208294 -0.59497023]
  [ 0.          0.          0.        ]
  [-0.34653513 -0.69841202 -0.36816274]]

 [[-0.02458136 -0.06367092 -0.2268075 ]
  [ 0.34653513  0.69841202  0.36816274]
  [ 0.          0.          0.        ]]]
Distance:
 [[        inf  1.07248743  0.05609987]
 [ 1.07248743         inf  0.74340974]
 [ 0.05609987  0.74340974         inf]]
i : [2 2 0]
i[:n] : [2 2 0]


In [42]:
from sklearn.neighbors import NearestNeighbors
d, i = NearestNeighbors().fit(X).kneighbors(X,2)
print(i[:3,1])


[1 0 1 1]
