In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## Creating a serie a let pandas create the index


In [3]:
s = pd.Series([1,3,7,np.nan, 9, 10])
s

0     1.0
1     3.0
2     7.0
3     NaN
4     9.0
5    10.0
dtype: float64

## Dates


In [9]:
dates = pd.date_range('20161006', periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
print(df)


DatetimeIndex(['2016-10-06', '2016-10-07', '2016-10-08', '2016-10-09',
               '2016-10-10', '2016-10-11'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2016-10-06  1.114974 -1.414888 -0.415034  1.157864
2016-10-07  0.895094 -0.445768  0.323698  0.943734
2016-10-08 -0.086677  1.264045 -0.022873 -0.855546
2016-10-09  0.172448 -2.000734 -0.359776 -0.379633
2016-10-10 -0.713382 -1.717050 -0.567398 -0.178038
2016-10-11  0.089541 -0.517185  0.345298  0.632937


In [11]:
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo' })
print(df2)
print(df2.dtypes)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


## Data visualization

In [13]:
df.head(3)

A         B         C         D
2016-10-06  1.114974 -1.414888 -0.415034  1.157864
2016-10-07  0.895094 -0.445768  0.323698  0.943734
2016-10-08 -0.086677  1.264045 -0.022873 -0.855546

In [14]:
df.tail(3)

A         B         C         D
2016-10-09  0.172448 -2.000734 -0.359776 -0.379633
2016-10-10 -0.713382 -1.717050 -0.567398 -0.178038
2016-10-11  0.089541 -0.517185  0.345298  0.632937

In [16]:
print('index: ', df.index)
print('columns: ', df.columns)
print('values: ', df.values)

index:  DatetimeIndex(['2016-10-06', '2016-10-07', '2016-10-08', '2016-10-09',
               '2016-10-10', '2016-10-11'],
              dtype='datetime64[ns]', freq='D')
columns:  Index(['A', 'B', 'C', 'D'], dtype='object')
values:  [[ 1.11497387 -1.41488821 -0.41503401  1.1578644 ]
 [ 0.89509361 -0.44576817  0.32369795  0.94373422]
 [-0.08667659  1.26404468 -0.02287254 -0.85554615]
 [ 0.17244794 -2.00073427 -0.35977586 -0.37963263]
 [-0.71338178 -1.71705026 -0.56739824 -0.17803813]
 [ 0.08954054 -0.5171846   0.3452983   0.63293729]]


In [17]:
print('describe (quick statistics):', df.describe())

describe (quick statistics):               A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.245333 -0.805263 -0.116014  0.220220
std    0.668941  1.193852  0.391768  0.806063
min   -0.713382 -2.000734 -0.567398 -0.855546
25%   -0.042622 -1.641510 -0.401219 -0.329234
50%    0.130994 -0.966036 -0.191324  0.227450
75%    0.714432 -0.463622  0.237055  0.866035
max    1.114974  1.264045  0.345298  1.157864


### transposing data

In [18]:
print('df.transpose()', df.T)

df.transpose()    2016-10-06  2016-10-07  2016-10-08  2016-10-09  2016-10-10  2016-10-11
A    1.114974    0.895094   -0.086677    0.172448   -0.713382    0.089541
B   -1.414888   -0.445768    1.264045   -2.000734   -1.717050   -0.517185
C   -0.415034    0.323698   -0.022873   -0.359776   -0.567398    0.345298
D    1.157864    0.943734   -0.855546   -0.379633   -0.178038    0.632937


## Sorting by an axis


In [27]:
print('sort col in reverse order: \n')
df.sort_index(axis=1, ascending=False)

sort col in reverse order: 



D         C         B         A
2016-10-06  1.157864 -0.415034 -1.414888  1.114974
2016-10-07  0.943734  0.323698 -0.445768  0.895094
2016-10-08 -0.855546 -0.022873  1.264045 -0.086677
2016-10-09 -0.379633 -0.359776 -2.000734  0.172448
2016-10-10 -0.178038 -0.567398 -1.717050 -0.713382
2016-10-11  0.632937  0.345298 -0.517185  0.089541

In [28]:
print('sort rows in reverse order: \n')
df.sort_index(axis=0, ascending=False)

sort rows in reverse order: 



A         B         C         D
2016-10-11  0.089541 -0.517185  0.345298  0.632937
2016-10-10 -0.713382 -1.717050 -0.567398 -0.178038
2016-10-09  0.172448 -2.000734 -0.359776 -0.379633
2016-10-08 -0.086677  1.264045 -0.022873 -0.855546
2016-10-07  0.895094 -0.445768  0.323698  0.943734
2016-10-06  1.114974 -1.414888 -0.415034  1.157864

## Sort by values

In [29]:
print('sort by B column:')
df.sort_values(by='B')

sort by B column:


A         B         C         D
2016-10-09  0.172448 -2.000734 -0.359776 -0.379633
2016-10-10 -0.713382 -1.717050 -0.567398 -0.178038
2016-10-06  1.114974 -1.414888 -0.415034  1.157864
2016-10-11  0.089541 -0.517185  0.345298  0.632937
2016-10-07  0.895094 -0.445768  0.323698  0.943734
2016-10-08 -0.086677  1.264045 -0.022873 -0.855546

## Selection

In [30]:
df['A']

2016-10-06    1.114974
2016-10-07    0.895094
2016-10-08   -0.086677
2016-10-09    0.172448
2016-10-10   -0.713382
2016-10-11    0.089541
Freq: D, Name: A, dtype: float64

In [31]:
df[0:2]

A         B         C         D
2016-10-06  1.114974 -1.414888 -0.415034  1.157864
2016-10-07  0.895094 -0.445768  0.323698  0.943734

In [32]:
df['20161008':'20161010']

A         B         C         D
2016-10-08 -0.086677  1.264045 -0.022873 -0.855546
2016-10-09  0.172448 -2.000734 -0.359776 -0.379633
2016-10-10 -0.713382 -1.717050 -0.567398 -0.178038

In [34]:
df.loc[dates[2]]

A   -0.086677
B    1.264045
C   -0.022873
D   -0.855546
Name: 2016-10-08 00:00:00, dtype: float64

In [35]:
df.loc[:,['A','B']]

A         B
2016-10-06  1.114974 -1.414888
2016-10-07  0.895094 -0.445768
2016-10-08 -0.086677  1.264045
2016-10-09  0.172448 -2.000734
2016-10-10 -0.713382 -1.717050
2016-10-11  0.089541 -0.517185

In [36]:
df.loc['20161008':'20161010', ['B', 'C']]

B         C
2016-10-08  1.264045 -0.022873
2016-10-09 -2.000734 -0.359776
2016-10-10 -1.717050 -0.567398

In [37]:
df.loc['20161011', ['A', 'B']]

A    0.089541
B   -0.517185
Name: 2016-10-11 00:00:00, dtype: float64

In [40]:
print(df.loc[dates[1], 'B'])
print('or even faster')
print(df.at[dates[1], 'B'])

-0.445768170264
or even faster
-0.445768170264


## Selection by position


In [41]:
df.iloc[3]

A    0.172448
B   -2.000734
C   -0.359776
D   -0.379633
Name: 2016-10-09 00:00:00, dtype: float64

In [42]:
df.iloc[:, 2]

2016-10-06   -0.415034
2016-10-07    0.323698
2016-10-08   -0.022873
2016-10-09   -0.359776
2016-10-10   -0.567398
2016-10-11    0.345298
Freq: D, Name: C, dtype: float64

### slicing (similar to python)



In [44]:
df.iloc[2:4,1:3]

B         C
2016-10-08  1.264045 -0.022873
2016-10-09 -2.000734 -0.359776

In [49]:
df.iloc[[1,3,5], [1,2]]

B         C
2016-10-07 -0.445768  0.323698
2016-10-09 -2.000734 -0.359776
2016-10-11 -0.517185  0.345298